### ISSUE TITLE
ASP.NET5 Class Library Does Not Compile

### ISSUE THREAD

**Issue by Michael-DST** [aspnet/Tooling#141]
I am attempting to put together my first ASP.NET5 and UWP solution.  In the process of doing so, I created a .SLN solution that you can find here:

https://github.com/Michael-DST/Stash/tree/master/TestBed

The problem is the "TestBed" ASP.NET Class Library Project that has a reference to a PCL library that is ASP.NET5-enabled.  If you try compiling this, you should get the following exception in the output:

```
Restoring packages for C:\Users\micha\OneDrive\Documents\Visual Studio 2015\Projects\Stash\TestBed\src\TestBed\project.json
  CACHE https://api.nuget.org/v3/index.json
  GET https://az320820.vo.msecnd.net/v3-flatcontainer/classlibrary1/index.json
Warning: FindPackagesById: ClassLibrary1
  Response from https://az320820.vo.msecnd.net/v3-flatcontainer/classlibrary1/index.json is not a valid NuGet v3 service response. The response doesn't contain 'versions' property.
  GET https://az320820.vo.msecnd.net/v3-flatcontainer/classlibrary1/index.json
Warning: FindPackagesById: ClassLibrary1
  Response from https://az320820.vo.msecnd.net/v3-flatcontainer/classlibrary1/index.json is not a valid NuGet v3 service response. The response doesn't contain 'versions' property.
  GET https://az320820.vo.msecnd.net/v3-flatcontainer/classlibrary1/index.json
Error: FindPackagesById: ClassLibrary1
  Response from https://az320820.vo.msecnd.net/v3-flatcontainer/classlibrary1/index.json is not a valid NuGet v3 service response. The response doesn't contain 'versions' property.
----------
System.IO.InvalidDataException: Response from https://az320820.vo.msecnd.net/v3-flatcontainer/classlibrary1/index.json is not a valid NuGet v3 service response. The response doesn't contain 'versions' property.
   at Microsoft.Framework.PackageManager.Restore.NuGet.NuGetv3Feed.EnsureValidFindPackagesResponse(Stream stream, String uri)
   at Microsoft.Framework.PackageManager.Restore.NuGet.NuGetv3Feed.<>c__DisplayClass14_0.<FindPackagesByIdAsyncCore>b__0(Stream stream)
   at Microsoft.Framework.PackageManager.Restore.NuGet.HttpSource.<GetAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.Restore.NuGet.NuGetv3Feed.<FindPackagesByIdAsyncCore>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass69_0.<<Execute>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<Execute>d__69.MoveNext()
----------
Restore failed
```

Everything was straight-forward here and I simply created projects and added references.  It seems as if the class library is treating the PCL as a NuGet package and not a local project.  I used the "Add Reference..." dialog to add the reference.  Is there something completely obvious I am overlooking in this scenario?

**Comment by Eilon** [comment]
@ChengTian can you take a look?

**Comment by Michael-DST** [comment]
Great, thank you @Eilon!  It is great to see a responsive and engaging team on here. :+1:

**Comment by davidfowl** [comment]
Might be a caching issue.

**Comment by ChengTian** [comment]
@Michael-DST , to resolve your problem, you can simply add `ClassLibrary1` into `projects` path by having `global.json` like:
```
{
    "projects": [ "src", "test", "ClassLibrary1" ],
    "sdk": {
        "version": "1.0.0-beta6"
    }
}
```
Otherwise our project system doesn't know you want to use your own `ClassLibrary1` project and it thinks `ClassLibrary1` is a NuGet package. That's why it's trying to restore `ClassLibrary1` from remote feeds.

@Michael-DST , please let us know whether it help.

Also, this does reveal another problem in our v3 feed handling logic. I filed an issue here: https://github.com/aspnet/dnx/issues/2447

**Comment by Michael-DST** [comment]
Great @ChengTian!  Thank you for looking into this, and for letting me know.  I will get a hang of this new project.json soon enough.

**Comment by Michael-DST** [comment]
OK I actually just tried your suggestion, and now I am getting 2 new errors:

```
1>C:\...\project.json(7,26): .NET Platform error : The dependency Microsoft.NETCore >= 5.0.0 could not be resolved.
1>C:\...\project.json(8,49): .NET Platform error : The dependency Microsoft.NETCore.Portable.Compatibility >= 1.0.0 could not be resolved.
```

Also, why was my global.json not updated with my PCL reference when I added it to my solution?

**Comment by davidfowl** [comment]
Adding it to the solution wouldn't update `global.json` but adding a reference to it from a project should.

**Comment by Michael-DST** [comment]
So is there another issue here then?  The global.json did not update when I added a reference to ClassLibrary1 (PCL) to TestBed (ASP.NET).  Please note that I am using Right Click References -> Add Reference ... approach and not one of the new fangled alternatives you kids are using these days. :stuck_out_tongue:

**Comment by sayedihashimi** [comment]
@davidfowl is this a tooling issue or runtime issue?

**Comment by sayedihashimi** [comment]
Closing this as I think this is a dnx issue and not specific to Visual Studio. In addition to this I think changes are in progress, or already made, to not confuse projects with packages.

If there is anything specific to VS please reopen with some details.
