### ISSUE TITLE
VS 2015 TestExplorer "Unable to read data from the transport connection" when discoverinig Xunit tests

### ISSUE THREAD

**Issue by bitcrazed** [aspnet/Tooling#166]
Wanted to raise this issue I logged under "Testing": https://github.com/aspnet/Testing/issues/146
Adding here because `Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases()` is in the call stack so may be related to the ASP.NET test discoverer:

```
------ Discover test started ------
------ Test started: Project: FOOBAR.Storage.Test ------
Starting  Microsoft.Framework.TestHost [C:\Users\rich\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta6\bin\dnx.exe --appbase "D:\Dev\AppDoggie\FOOBAR\test\FOOBAR.Storage.Test" Microsoft.Framework.ApplicationHost --port 65453 Microsoft.Framework.TestHost --port 65478]
Connected to Microsoft.Framework.TestHost
Discovering tests in 'D:\Dev\AppDoggie\FOOBAR\test\FOOBAR.Storage.Test\project.json'
Error discovering tests in 'D:\Dev\AppDoggie\FOOBAR\test\FOOBAR.Storage.Test\project.json'
System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
========== Discover test finished: 0 found (0:00:13.2069858) ==========
```

**Comment by sayedihashimi** [comment]
@bitcrazed from https://github.com/aspnet/Testing/issues/146 I can see that you've resolved this. Is there any updated needed from us?

**Comment by sayedihashimi** [comment]
@bitcrazed I'm closing this because it seems like the issue has been resolved from comments at https://github.com/aspnet/Testing/issues/146. If this is still an issue please reopen this with more details.
