### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#184]
_From @JamesNK on August 2, 2015 11:20_

I intermittently get the error below. Running tests from VS2015, beta 6.

```
------ Run test started ------
------ Test started: Project: Newtonsoft.Json.Tests ------
Starting  Microsoft.Framework.TestHost [C:\Users\James\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta6\bin\dnx.exe --appbase "C:\Development\Source\Json\Newtonsoft.Json\Src\Newtonsoft.Json.Tests" Microsoft.Framework.ApplicationHost --port 42091 Microsoft.Framework.TestHost --port 42969]
Connected to Microsoft.Framework.TestHost
Discovering tests in 'C:\Development\Source\Json\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\project.json'
------ Test started: Project: Newtonsoft.Json.Tests ------
Starting  Microsoft.Framework.TestHost [C:\Users\James\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta6\bin\dnx.exe --appbase "C:\Development\Source\Json\Newtonsoft.Json\Src\Newtonsoft.Json.Tests" Microsoft.Framework.ApplicationHost --port 42091 Microsoft.Framework.TestHost --port 42975]
Connected to Microsoft.Framework.TestHost
Running tests in 'C:\Development\Source\Json\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\project.json'
Error running tests in 'C:\Development\Source\Json\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\project.json'\r\nSystem.Exception: Could not convert string to DateTimeOffset: 0001. Path 'StartTime'.
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Executor.HostExtensions.ExecuteTests(IHost host, IFrameworkHandle framework, IEnumerable`1 tests)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, Boolean isRunAllTests)
````

_Copied from original issue: aspnet/Testing#135_

**Comment by sayedihashimi** [comment]
TFS:149246

**Comment by barrytang** [comment]
@JamesNK, can you still repro this with Beta8?

**Comment by JamesNK** [comment]
Nope

**Comment by sayedihashimi** [comment]
Ok thanks closing
