### ISSUE TITLE
When unit testing through Visual Studio "Run All" button does not run all unit tests

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Tooling#288]
When running all unit tests in Visual Studio with latest tooling and rc1 versions of everything (CLR, ASP.NET MVC, Xunit) when you click on "Run All" button, not all tests are run. For example: in my project I have around 200 unit tests but only 5% run. Also they run at random and not every time the run tests are the same. To run all of them I need to manually select all - right click of the mouse - and click "Run Selected Tests".

**Comment by sayedihashimi** [comment]
@ivaylokenov I have not seen this. Could you share the solution that you are seeing this in?

**Comment by ivaylokenov** [comment]
@sayedihashimi After the latest Visual Studio 2015 upgrade, I could not reproduce the problem.

**Comment by ivaylokenov** [comment]
@sayedihashimi Now I started getting the following when running tests:

Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Executor.HostExtensions.ExecuteTests(IHost host, IFrameworkHandle framework, IEnumerable`1 tests)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestExecutor.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, Boolean isRunAllTests)

**Comment by sayedihashimi** [comment]
@ivaylokenov thanks I'll go ahead and close this now.
