### ISSUE TITLE
Error loading .xproj in an existing solution and when adding to another solution

### ISSUE THREAD

**Issue by NickCraver** [aspnet/Tooling#493]
Here's an exact commit to pull (this was an in-progress RC2 upgrade): https://github.com/StackExchange/StackExchange.Redis/tree/9c4a35bff8f162ba2e8e6be7bf5f21906c7e9b5a

Loading the `StackExchange.Redis.dnx.sln` causes one error for each project:
```
Recoverable
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.DotNet.Publish.PublishLoader.<<Initialize>b__13_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DotNet.Publish.PublishLoader.<Initialize>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__6_0>d.MoveNext()
```

I also get a DNX warning on-load of the solution, but I am unsure if it is related:
> DNX SDK version 'dnx-clr-win-x86.1.0.0-rc1-final' is required by your solution but is not installed on this machine. Do you want to install it now? If you select No, you can still work with your project but the experience will be degraded.

The load error/stack above is also reproducible when trying to add (Add -> Existing Project) the `.xproj` to the other `StackExchange.Redis.sln` (I am trying to consolidate projects now). Additionally, adding a `project.json` directly there simply fails with: 
> The operation could not be completed

...and no further detail. I am unsure if these are 3 independent issues or all inter-related, but starting with the most information first. If I should break any of these into other issues, I'm happy to.

**Comment by NickCraver** [comment]
Update: the DNX error was from an old `global.json`. The other 2 persist. Here are my `global.json` changes in case others come across this:

Old:
```json
{
  "sdk": {
    "version": "1.0.0-rc1-final",
    "runtime": "coreclr",
    "architecture": "x86"
  },
  "projects": [ "StackExchange.Redis_dnxcore50" ]
}
```
New:
```json
{
  "sdk": {
    "version": "1.0.0-preview1-002702"
  }
}
```

**Comment by sayedihashimi** [comment]
TFS: 223011
I've added this to our internal TFS, we will reply back here soon.

**Comment by vijayrkn** [comment]
@NickCraver I am currently looking into this issue. I tried loading the StackExchange.Redis.dnx.sln from here (https://github.com/StackExchange/StackExchange.Redis/tree/9c4a35bff8f162ba2e8e6be7bf5f21906c7e9b5a) but it is loading without any issues. I also tried building the solution and it builds fine. 

Is this still an issue? If so, can you please provide the exact repro steps?

**Comment by NickCraver** [comment]
@vijayrkn I'm not seeing this with latest tooling - whatever upgrade artifact hosed Visual Studio in preview 1, the same doesn't exist in preview 2. Since no one else has chimed in hitting the same scenario, I'll close this out.
