### ISSUE TITLE
ProjectException: "Duplicated source project item"

### ISSUE THREAD

**Issue by meolafon** [aspnet/Tooling#544]
(copied from https://github.com/dotnet/coreclr/issues/5168)

Trying to run T4 transforms on 'Build' in xproj file.

1)
If "MyTemplate.tt" is inside of project, but not mentioned in xproj file directly, Microsoft.TextTemplating.targets cannot see it:
(output from build)

_....
Target "ExecuteTransformations" in file...
Full list of templates passed in :
1> {none}
....
1>Done building target "ExecuteTransformations" in project "MyProject.xproj".
(end)_

In other words, nothing gets created from the template.

2)
If "MyTemplate" is mentioned in xproj as

```
  <ItemGroup>
      <None Include="MyTemplate.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <OutputFilePath>\somepath\</OutputFilePath>
      </None>
</ItemGroup>
```

I cannot open the project, with the following exception:

_System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.ProjectSystem.ProjectException: Duplicated source project item: "MyTemplate.tt".
at Microsoft.VisualStudio.ProjectSystem.Utilities.ProjectErrorUtilities.ThrowProjectExceptionHelper(Exception innerException, String unformattedMessage, Object[] args)
at Microsoft.VisualStudio.ProjectSystem.Utilities.ProjectErrorUtilities.ThrowProjectException(String message, Object arg0)
at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.CollectAllItemsInProjectTree(IImmutableDictionary2 currentProjectData, Dictionary2 pendingItemsByDirectory, ConfiguredProjectExports configuredProjectExports)
at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.d__115.MoveNext()_

PS: Hopefully, the problem will fix itself when xproj is gone and csproj is back, but in the meantime I have found no workaround - only click "Run custom tool" manually

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231160&fullScreen=false&_a=edit">231160</a>

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.
