### ISSUE TITLE
How do I address the Razor Shim CreateTrackingSpan error that Visual Studio keeps logging?

### ISSUE THREAD

**Issue by jrood** [aspnet/Tooling#590]
I can see many entries in my ActivityLog that have a stack trace like this

<pre>
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.VisualStudio.Text.Implementation.TrackingSpan..ctor(ITextVersion version, Span span, SpanTrackingMode trackingMode)
   at Microsoft.VisualStudio.Text.Implementation.TextVersion.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode, TrackingFidelityMode trackingFidelity)
   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode)
   at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorSpanClassifier.OnSpansChanged(Object sender, SpansChangedEventArgs eventArgs)
   at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorCodeGenerator.add_SpansChanged(EventHandler 1 value)
   at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorSpanClassifier.EnsureInitialized()
   at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorSpanClassifier.Microsoft.VisualStudio.Text.Classification.IClassifier.GetClassificationSpans(SnapshotSpan toClassifySpan)
   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext()
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator 1.<GetTagsForBuffer>d__38.MoveNext()
</pre>

How would I address this problem?

**Comment by sayedihashimi** [comment]
TFS Bug#232008

**Comment by ToddGrun** [comment]
Took a peek at the code and I'm not seeing how we're getting invalid positions. @jrood, could you capture a dump file at the time of the exception being thrown and share it it? Thanks!

**Comment by jrood** [comment]
@ToddGrun although I got a bunch of those log messages yesterday, unfortunately I haven't been able to reproduce it today.

**Comment by mlorbetske** [comment]
Since there hasn't been an update here in over a year, closing this one. If you run in to this again, please report it on the [developer community](https://developercommunity.visualstudio.com/) site.
