### ISSUE TITLE
VS Crash when attempting to update rc2 packages to latest version

### ISSUE THREAD

**Issue by niemyjski** [aspnet/Tooling#615]
I'm running Windows 10 RTM (Non insiders) & VS2015 Update 3 RTM.

I tried to update my nuget packages via the nuget dialog for my solution (https://github.com/exceptionless/Exceptionless.Net) from rc2 (there were about 35 of them) and I kept on getting crashes..

```
Log Name:      Application
Source:        Application
Date:          6/26/16 12:20:41 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BLAKENIEMYJF00D
Description:
The description for Event ID 0 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Error Handler Exception: System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---> System.IO.PipeException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d).
   at System.ServiceModel.Channels.PipeConnection.OnAsyncReadComplete(Boolean haveResult, Int32 error, Int32 numBytes)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ConnectionStream.EndRead(IAsyncResult asyncResult)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.EndRead(IAsyncResult asyncResult)
   at System.ServiceModel.Channels.StreamConnection.EndRead()
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext)
   at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext) \r\n    at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext)
   at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext)

the message resource is present but the message is not found in the string/message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-06-26T17:20:41.142593600Z" />
    <EventRecordID>35175</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BLAKENIEMYJF00D</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Error Handler Exception: System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---&gt; System.IO.IOException: The read operation failed, see inner exception. ---&gt; System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---&gt; System.IO.PipeException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d).
   at System.ServiceModel.Channels.PipeConnection.OnAsyncReadComplete(Boolean haveResult, Int32 error, Int32 numBytes)
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ConnectionStream.EndRead(IAsyncResult asyncResult)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.EndRead(IAsyncResult asyncResult)
   at System.ServiceModel.Channels.StreamConnection.EndRead()
   --- End of inner exception stack trace ---
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message&amp; message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext&amp; requestContext)
   at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext&amp; requestContext) \r\n    at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message&amp; message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext&amp; requestContext)
   at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext&amp; requestContext)</Data>
  </EventData>
</Event>
```

```
Log Name:      Application
Source:        Windows Error Reporting
Date:          6/26/16 12:20:41 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BLAKENIEMYJF00D
Description:
Fault bucket 129144297448, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 14.0.25420.1
P3: 57685d85
P4: mscorlib
P5: 4.6.1080.0
P6: 570c5040
P7: 3955
P8: 18
P9: System.OutOfMemoryException
P10: 

Attached files:
C:\Users\blake\AppData\Local\Microsoft\VSCommon\14.0\SQM\sqmdata.cvr
C:\Users\blake\AppData\Local\Temp\WERD384.tmp.WERInternalMetadata.xml
C:\Users\blake\AppData\Local\Temp\WERDD98.tmp.appcompat.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_devenv.exe_e9b684cbe46013962059cb89a3113c7c60868889_12aa736e_1c3b0301

Analysis symbol: 
Rechecking for solution: 0
Report Id: e2d043ba-48af-497c-80ba-6e79457f7ca3
Report Status: 1
Hashed bucket: 2a50daa7ba03c99d01dfcd5f85da01f2
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-06-26T17:20:41.290224300Z" />
    <EventRecordID>35176</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BLAKENIEMYJF00D</Computer>
    <Security />
  </System>
  <EventData>
    <Data>129144297448</Data>
    <Data>5</Data>
    <Data>CLR20r3</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>devenv.exe</Data>
    <Data>14.0.25420.1</Data>
    <Data>57685d85</Data>
    <Data>mscorlib</Data>
    <Data>4.6.1080.0</Data>
    <Data>570c5040</Data>
    <Data>3955</Data>
    <Data>18</Data>
    <Data>System.OutOfMemoryException</Data>
    <Data>
    </Data>
    <Data>
C:\Users\blake\AppData\Local\Microsoft\VSCommon\14.0\SQM\sqmdata.cvr
C:\Users\blake\AppData\Local\Temp\WERD384.tmp.WERInternalMetadata.xml
C:\Users\blake\AppData\Local\Temp\WERDD98.tmp.appcompat.txt</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_devenv.exe_e9b684cbe46013962059cb89a3113c7c60868889_12aa736e_1c3b0301</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>e2d043ba-48af-497c-80ba-6e79457f7ca3</Data>
    <Data>1</Data>
    <Data>2a50daa7ba03c99d01dfcd5f85da01f2</Data>
  </EventData>
</Event>
```

I also got this error as well 20 seconds earlier:

```
Log Name:      Application
Source:        .NET Runtime
Date:          6/26/16 12:20:24 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BLAKENIEMYJF00D
Description:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Threading.ExecutionContext.CreateCopy()
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(System.Object)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-06-26T17:20:24.566882400Z" />
    <EventRecordID>35172</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BLAKENIEMYJF00D</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Threading.ExecutionContext.CreateCopy()
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(System.Object)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

</Data>
  </EventData>
</Event>
```

```
Log Name:      Application
Source:        Application Error
Date:          6/26/16 12:20:28 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BLAKENIEMYJF00D
Description:
Faulting application name: devenv.exe, version: 14.0.25420.1, time stamp: 0x57685d85
Faulting module name: KERNELBASE.dll, version: 10.0.10586.306, time stamp: 0x571afb9a
Exception code: 0xe0434352
Fault offset: 0x000bdae8
Faulting process id: 0x19f8
Faulting application start time: 0x01d1cfcc7a0113d5
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: e2d043ba-48af-497c-80ba-6e79457f7ca3
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-06-26T17:20:28.082723900Z" />
    <EventRecordID>35173</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BLAKENIEMYJF00D</Computer>
    <Security />
  </System>
  <EventData>
    <Data>devenv.exe</Data>
    <Data>14.0.25420.1</Data>
    <Data>57685d85</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10586.306</Data>
    <Data>571afb9a</Data>
    <Data>e0434352</Data>
    <Data>000bdae8</Data>
    <Data>19f8</Data>
    <Data>01d1cfcc7a0113d5</Data>
    <Data>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe</Data>
    <Data>C:\Windows\SYSTEM32\KERNELBASE.dll</Data>
    <Data>e2d043ba-48af-497c-80ba-6e79457f7ca3</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

```
Microsoft Visual Studio Enterprise 2015
Version 14.0.25420.01 Update 3
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA180
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA180
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA180
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA180
Microsoft Visual C++ 2015

Visual F# 2015   00322-80000-00000-AA180
Microsoft Visual F# 2015

Add New File   3.4
The fastest and easiest way to add new files to any project - including files that start with a dot

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Bundler & Minifier   2.0.235
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

Editor Enhancements   1.0.19
Provides additional features such as HTML and URL encodings, transformations and sorting of selected text the editor.

Exception Breaker   1.0
Simplifies "Break On Exception" UI.

File Nesting   2.5.62
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Image Optimizer   3.6.89
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites   1.2.36
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.2 EAP 5   Build 106.0.20160623.165258-eap5
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Markdown Editor   1.3.81
A full featured Markdown editor with live preview and syntax highligting. Supports GitHub flavored Markdown.

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40211.2

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.175
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40315.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40315.00
Profiling support for Python projects.

Rebracer   1.0
Saves editor formatting settings as part of each solution.

SQL Server Data Tools   14.0.60525.0
Microsoft SQL Server Data Tools

TargetFrameworkMigrator   1.0
Bulk Change .Net Projects Target Frameworks

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.34.0
TypeScript tools for Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25208.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Compiler   1.11.315
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.3   3.0.230
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Xamarin   4.0.1.96 (dcea9c1)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.1.10 (e98e962)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.4.1.24 (47eb74b)
Visual Studio extension to enable development for Xamarin.iOS.
```

**Comment by niemyjski** [comment]
Just got this same crash while debugging.

**Comment by barrytang** [comment]
TFS Bug#235752

**Comment by mlorbetske** [comment]
@niemyjski can you capture a dump if this happens again so we can analyze it please?
