### ISSUE TITLE
Unable to start program “C:\Program Files\dotnet\dotnet.exe”

### ISSUE THREAD

**Issue by lkinsella** [aspnet/Tooling#807]
I've installed .NET Core 1.0.1 to use with VS 2015 Update 3 and I'm running as Administrator.

If I create *any* .NET Core project, be it console or web and attempt to run it Visual Studio then comes up with an error:

[![enter image description here][1]][1]

However I'm unable to ascertain why. I can run it from the CLI fine and non .NET Core works fine.

I've tried:

- Deleting `project.lock.json`
- Deleting the `.vs` folder
- Repairing the .NET Core install
- Repairing the VS 2015 install
- Uninstalling and reinstalling .NET Core/SDK/Tooling
- Rebooting

And it still refuses to work!

Anyone have any thoughts or come across this before? Kind of dead in the water Core wise until it's resolved.

  [1]: http://i.stack.imgur.com/9UHuU.png

**Comment by mlorbetske** [comment]
@lkinsella are your running a x86 or x64 version of Windows?

**Comment by lkinsella** [comment]
Windows 8.1 x64, generally running VS as an Administrator as well.

**Comment by mlorbetske** [comment]
Does `c:\program files\dotnet\dotnet.exe` exist? How about `c:\program files (x86)\dotnet\dotnet.exe`?

**Comment by lkinsella** [comment]
`c:\program files\dotnet\dotnet.exe` exists, `c:\program files (x86)\dotnet\dotnet.exe` does not (no `dotnet` folder at all for that one).

I installed the x86 SDK installer and that created the latter (I've uninstalled it now), however VS still didn't play ball.

I also tried VS Code and that can run and debug fine.

**Comment by mlorbetske** [comment]
@abpiskunov any ideas?

**Comment by lkinsella** [comment]
I may try completely uninstalling VS and Core over the weekend and then reinstalling and see what happens.

**Comment by abpiskunov** [comment]
In your case we just run it via cmd line shell. Sample command line would look like this: C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\dotnet\dotnet.exe" "c:\users\xxx\documents\visual studio 2015\Projects\ConsoleApp4\src\ConsoleApp4\bin\Debug\netcoreapp1.0\ConsoleApp4.dll"  & pause"

So it looks like cmd shell is complaining in your case and i am wondering what would be different on your machine. 

Before running that command line we also merge all env variables for that process. So all env vars from current VS instance also would flow there.

**Comment by lkinsella** [comment]
Yeh I can definitely manually do a build and run from the CLI but I'll try something akin to the above and see what the envars are like when I get in.

I'll report back later.

**Comment by lkinsella** [comment]
So I tried the command line you specified and that runs fine.

I also uninstalled and reinstalled both VS2015 and .NET Core but it's still throwing the error.

Environment variables for VS (according to Process Explorer):

```
ALLUSERSPROFILE	C:\ProgramData
APPDATA	C:\Users\Lloyd\AppData\Roaming
CommonProgramFiles	C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)	C:\Program Files (x86)\Common Files
CommonProgramW6432	C:\Program Files\Common Files
COMPUTERNAME	OSIRIS
ComSpec	C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK	NO
GIT_SSH	C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
HOMEDRIVE	C:
HOMEPATH	\Users\Lloyd
LOCALAPPDATA	C:\Users\Lloyd\AppData\Local
LOGONSERVER	\\OSIRIS
MSBuildLoadMicrosoftTargetsReadOnly	true
NUMBER_OF_PROCESSORS	8
OS	Windows_NT
Path	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\Program Files\PHP\v7.0;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\;C:\Users\Lloyd\.dnx\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\RemObjects Software\Oxfuscator\bin;C:\Program Files\Tort;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\Lloyd\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-update2\bin;C:\Users\Lloyd\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
PATHEXT	.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PkgDefApplicationConfigFile	C:\Users\Lloyd\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
PROCESSOR_ARCHITECTURE	x86
PROCESSOR_ARCHITEW6432	AMD64
PROCESSOR_IDENTIFIER	Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL	6
PROCESSOR_REVISION	3c03
ProgramData	C:\ProgramData
ProgramFiles	C:\Program Files (x86)
ProgramFiles(x86)	C:\Program Files (x86)
ProgramW6432	C:\Program Files
PSModulePath	C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\
PUBLIC	C:\Users\Public
SESSIONNAME	Console
SVN_SSH	C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SystemDrive	C:
SystemRoot	C:\Windows
TEMP	C:\Users\Lloyd\AppData\Local\Temp
TMP	C:\Users\Lloyd\AppData\Local\Temp
USERDOMAIN	OSIRIS
USERDOMAIN_ROAMINGPROFILE	OSIRIS
USERNAME	Lloyd
USERPROFILE	C:\Users\Lloyd
VBOX_MSI_INSTALL_PATH	C:\Program Files\Oracle\VirtualBox\
VisualStudioDir	D:\Lloyd\Documents\Visual Studio 2015
VisualStudioEdition	Microsoft Visual Studio Community 2015
VisualStudioVersion	14.0
VS110COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VS120COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VS140COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSLANG	1033
VSSDK140Install	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
windir	C:\Windows
```

**Comment by abpiskunov** [comment]
i see that you have .dnx paths in your PATH env variable. Could you try to remove them just in case?

**Comment by lkinsella** [comment]
I've nuked those but same issue. I've included the latest environment below for both VS and the instance of dotnet it appears to load, which I find odd as if it loads an instance (I assume for compilation/restore) then how does it not start?

devenv.exe:

```
__COMPAT_LAYER	ElevateCreateProcess
ALLUSERSPROFILE	C:\ProgramData
APPDATA	C:\Users\Lloyd\AppData\Roaming
CommonProgramFiles	C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)	C:\Program Files (x86)\Common Files
CommonProgramW6432	C:\Program Files\Common Files
COMPLUS_InstallRoot	
COMPLUS_Version	
COMPUTERNAME	OSIRIS
ComSpec	C:\Windows\system32\cmd.exe
DOTNET_SKIP_FIRST_TIME_EXPERIENCE	1
FP_NO_HOST_CHECK	NO
GIT_SSH	C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
HOMEDRIVE	C:
HOMEPATH	\Users\Lloyd
LOCALAPPDATA	C:\Users\Lloyd\AppData\Local
LOGONSERVER	\\OSIRIS
MSBuildLoadMicrosoftTargetsReadOnly	true
NODE_PATH	C:\Users\Lloyd\AppData\Roaming\npm
NUMBER_OF_PROCESSORS	8
OS	Windows_NT
Path	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\Program Files\PHP\v7.0;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\RemObjects Software\Oxfuscator\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Lloyd\AppData\Roaming\npm
PATHEXT	.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PkgDefApplicationConfigFile	C:\Users\Lloyd\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
PROCESSOR_ARCHITECTURE	x86
PROCESSOR_ARCHITEW6432	AMD64
PROCESSOR_IDENTIFIER	Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL	6
PROCESSOR_REVISION	3c03
ProgramData	C:\ProgramData
ProgramFiles	C:\Program Files (x86)
ProgramFiles(x86)	C:\Program Files (x86)
ProgramW6432	C:\Program Files
PSModulePath	C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\
PUBLIC	C:\Users\Public
SVN_SSH	C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SystemDrive	C:
SystemRoot	C:\Windows
TEMP	C:\Users\Lloyd\AppData\Local\Temp
TMP	C:\Users\Lloyd\AppData\Local\Temp
USERDOMAIN	OSIRIS
USERDOMAIN_ROAMINGPROFILE	OSIRIS
USERNAME	Lloyd
USERPROFILE	C:\Users\Lloyd
VBOX_MSI_INSTALL_PATH	C:\Program Files\Oracle\VirtualBox\
VisualStudioDir	D:\Lloyd\Documents\Visual Studio 2015
VisualStudioEdition	Microsoft Visual Studio Community 2015
VisualStudioVersion	14.0
VS110COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VS120COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VS140COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSLANG	1033
WHOISIQ_PROVIDERS_DIR	P:\Workshell\WhoisIQ\Providers\Bin\Debug
windir	C:\Windows
```

dotnet.exe (attached to devenv.exe):

```
__COMPAT_LAYER	ElevateCreateProcess
ALLUSERSPROFILE	C:\ProgramData
APPDATA	C:\Users\Lloyd\AppData\Roaming
CommonProgramFiles	C:\Program Files\Common Files
CommonProgramFiles(x86)	C:\Program Files (x86)\Common Files
CommonProgramW6432	C:\Program Files\Common Files
COMPUTERNAME	OSIRIS
ComSpec	C:\Windows\system32\cmd.exe
DOTNET_SKIP_FIRST_TIME_EXPERIENCE	1
FP_NO_HOST_CHECK	NO
GIT_SSH	C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
HOMEDRIVE	C:
HOMEPATH	\Users\Lloyd
LOCALAPPDATA	C:\Users\Lloyd\AppData\Local
LOGONSERVER	\\OSIRIS
MSBuildLoadMicrosoftTargetsReadOnly	true
NODE_PATH	C:\Users\Lloyd\AppData\Roaming\npm
NUMBER_OF_PROCESSORS	8
OS	Windows_NT
Path	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\Program Files\PHP\v7.0;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\RemObjects Software\Oxfuscator\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Lloyd\AppData\Roaming\npm;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1
PATHEXT	.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PkgDefApplicationConfigFile	C:\Users\Lloyd\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
PROCESSOR_ARCHITECTURE	AMD64
PROCESSOR_IDENTIFIER	Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL	6
PROCESSOR_REVISION	3c03
ProgramData	C:\ProgramData
ProgramFiles	C:\Program Files
ProgramFiles(x86)	C:\Program Files (x86)
ProgramW6432	C:\Program Files
PSModulePath	C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\
PUBLIC	C:\Users\Public
SVN_SSH	C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
SystemDrive	C:
SystemRoot	C:\Windows
TEMP	C:\Users\Lloyd\AppData\Local\Temp
TMP	C:\Users\Lloyd\AppData\Local\Temp
USERDOMAIN	OSIRIS
USERDOMAIN_ROAMINGPROFILE	OSIRIS
USERNAME	Lloyd
USERPROFILE	C:\Users\Lloyd
VBOX_MSI_INSTALL_PATH	C:\Program Files\Oracle\VirtualBox\
VisualStudioDir	D:\Lloyd\Documents\Visual Studio 2015
VisualStudioEdition	Microsoft Visual Studio Community 2015
VisualStudioVersion	14.0
VS110COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VS120COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VS140COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSLANG	1033
VSSNSESLNASFLDR	1
WHOISIQ_PROVIDERS_DIR	P:\Workshell\WhoisIQ\Providers\Bin\Debug
windir	C:\Windows
```

**Comment by phillipsj** [comment]
I have the same issue.

Unable to start C:\Program Files\dotnet\dotnet.exe
dotnet-test Error: 0 : [ReportingChannel]: Waiting for message failed System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
dotnet-test Error: 0 : [ReportingChannel]: Error sending System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryWriter.Write7BitEncodedInt(Int32 value)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.Send(Message message)
dotnet-test Error: 0 : System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryWriter.Write7BitEncodedInt(Int32 value)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.Send(Message message)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.SendError(String error)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.SendError(Exception ex)
   at Microsoft.DotNet.Tools.Test.DesignTimeRunner.HandleDesignTimeMessages(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.DesignTimeRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.BaseDotnetTestRunner.RunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams, BuildWorkspace workspace)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
Discovering tests in 'C:\Users\cphil\code\cake\src\Cake.NuGet.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Users\cphil\code\cake\src\Cake.NuGet.Tests\project.json" --output "C:\Users\cphil\code\cake\src\Cake.NuGet.Tests\bin\Debug\netcoreapp1.0" --port 60606 --parentProcessId 11612 --no-build]
Discovering tests in 'C:\Users\cphil\code\cake\src\Cake.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Users\cphil\code\cake\src\Cake.Tests\project.json" --output "C:\Users\cphil\code\cake\src\Cake.Tests\bin\Debug\net451\win7-x64" --port 60611 --parentProcessId 11612 --no-build]
Unable to start C:\Program Files\dotnet\dotnet.exe
dotnet-test Error: 0 : [ReportingChannel]: Waiting for message failed System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
dotnet-test Error: 0 : [ReportingChannel]: Error sending System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryWriter.Write7BitEncodedInt(Int32 value)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.Send(Message message)
dotnet-test Error: 0 : System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryWriter.Write7BitEncodedInt(Int32 value)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.Send(Message message)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.SendError(String error)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.SendError(Exception ex)
   at Microsoft.DotNet.Tools.Test.DesignTimeRunner.HandleDesignTimeMessages(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.DesignTimeRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.BaseDotnetTestRunner.RunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams, BuildWorkspace workspace)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
========== Discover test finished: 13 found (0:00:04.5969861) ==========

**Comment by abpiskunov** [comment]
@phillipsj you don't have the same issue, you have what ever exception says: some software on your machine prevents connection between VS and dotnet.exe. We saw example of that when firewalls or anti viruses did that. Please see you environment settings. (in the issue above dotnet has connection with VS and only when app is executed a command shell -cmd does not run dotnet.exe)

**Comment by sebastianhoratiu** [comment]
Hi, has anyone had any luck finding the solution for this error?
I'm having the same error on Windows 7 Professional 64-bit. Tried all that was suggested above with no luck.

**Comment by abpiskunov** [comment]
There were 2 different issues mentioned in this thread (1. when project can be executed, 2. when VS can not even connect to dotnet.exe) - what error do you have?

**Comment by sebastianhoratiu** [comment]
The second one, "Unable to start program 'C:\Program Files\dotnet\dotnet.exe'.

**Comment by vijay-moharle** [comment]
Did you able to get it work sebastianhoratiu ? if yes can you please share ? I  have been scratching my head for  this issue which i encountered recently  while converting DNX project to  .Net core 1.1  .. any suggestion/help appreciated..

**Comment by sebastianhoratiu** [comment]
Unfortunately not. I think only a re-install of Windows would fix it.

**Comment by roduman** [comment]
It's decided!!!!!!!!!!!!!!!!!!!! Disable the program VPN.

**Comment by Surangaup** [comment]
Try with adding Path **"C:\Program Files\dotnet"** to environment variables.
