### ISSUE TITLE
Visual Studio RC 2015 Enterprise Crashes Constantly with project loaded in with Bower and NPM packages already loaded in the tree

### ISSUE THREAD

**Issue by xtianus79** [aspnet/Tooling#85]
I wanted to check if my grunt task processes would now be able to run with the new VS RC 2015 and I couldn't even get the project to load into VS. I do get an error message but this is far from stable as the previous CTP 6 version was.

Any thoughts?

https://github.com/xtianus79/generator-aspnet this git repo is different than the npm package as I work out the issues. so if you npm install -g xtianus79/generator-aspent will install the git version

@madskristensen @davidfowl

here is the file that generated @madskristensen @davidfowl 

          =====================
      5/27/2015 8:49:40 PM
      Recoverable
      System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The request to update the project tree was rejected. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
         at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
         at System.IO.Path.GetDirectoryName(String path)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindOrCreateExcludedItem(IProjectTree tree, String relativePath, String fullPath, Boolean alwaysInvisible)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<GenerateOriginalTreeAsync>d__115.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
         at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass94_0.<<Initialize>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass101_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext()
         --- End of inner exception stack trace ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at Microsoft.VisualStudio.ProjectSystem.Utilities.CommonProjectSystemTools.Rethrow(Exception ex)
         at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
         at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
         at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
         --- End of inner exception stack trace ---
      ---> (Inner Exception #0) System.InvalidOperationException: The request to update the project tree was rejected. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
         at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
         at System.IO.Path.GetDirectoryName(String path)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.FindOrCreateExcludedItem(IProjectTree tree, String relativePath, String fullPath, Boolean alwaysInvisible)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AddExcludedFiles(IProjectTree projectTree, IProjectTree directoryTreeStartingPoint, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
         at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<GenerateOriginalTreeAsync>d__115.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
         at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass94_0.<<Initialize>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass101_0.<<SubmitTreeUpdateAsync>b__0>d.MoveNext()
         --- End of inner exception stack trace ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at Microsoft.VisualStudio.ProjectSystem.Utilities.CommonProjectSystemTools.Rethrow(Exception ex)
         at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
         at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
         at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

      ===================

**Comment by barrytang** [comment]
TFS#1178892

**Comment by sayedihashimi** [comment]
@xtianus79 could you attach a sample project in a zip file?

**Comment by xtianus79** [comment]
can you  attach zip files here or should I email you?

**Comment by xtianus79** [comment]
@sayedihashimi @barrytang @BillHiebert yep... you can't attach zip files here but I will create a link to it in my dropbox.  

This project has not been built for npm install or bower install so it is just the file folder structure... Either way, built or not, it seems to try to build it upon loading in the project.json and just crashes out.  

https://www.dropbox.com/s/m5p7p3qam1vz38b/sampleProject_notBuilt.zip?dl=0 

let me know you have received it ok.

**Comment by xtianus79** [comment]
any update on this?

**Comment by abpiskunov** [comment]
@xtianus79  I tried to open project attached in the zip in both RC and our latest current version and it loads fine and installs all bower and npm packages. After it is loaded it builds fine.

What exactly did you mean by " it seems to try to build it upon loading in the project.json"?

I need detailed info or repro steps: 
- what is the folder structure where your project lives on your machine (exception says path is too long, I tried to put it to very deep folder and it still worked)? 
- what dnx versions you have installed? What is your default dnx alias?
- What settings do you have under Tools\Options\Projects and Solutions\External Web Tools?

**Comment by abpiskunov** [comment]
Also, when you said "crashed" did you mean that VS really crashed or you just so some error message or dialog? How did you get your stack trace?

**Comment by abpiskunov** [comment]
*saw

**Comment by AArnott** [comment]
The file that @xtianus79 includes with the original report suggests it wasn't a crash -- just an error dialog that mentioned a project failure occurred and pointed at the text file that is here included.

**Comment by abpiskunov** [comment]
Ok, @xtianus79 as Andrew mentioned in another thread, you need to put your solution to some shorter path and it should work,

**Comment by xtianus79** [comment]
@abpiskunov What? Wait a minute... that is not a solution.  Because first and foremost this was not an issue the beta builds I have built this generator on previously.  Everything was fine.  Do you think I am they only one with a grunt build?  Do you know how grunt works? It has node packages and bower packages... I am installing these on the root of my harddrive... there really isn't anywhere else to go from here?  Again, it was working before so there was something changed that looks at those files as before it didn't do that.  

@abpiskunov do you work for Microsoft?  Because it is kind of scary you would make that comment and seemingly not have a grasp on this product and what its functionalities are.  

I am asking you reopen this thread and properly bug test this out until a practical solution has occurred.  The path is too long... yes we know that.  However, MSFT is the one who decided to put grunt and gulp inside.  Now it needs to work as such.   

> Ok, @xtianus79 as Andrew mentioned in another thread, you need to put your solution to some shorter path and it should work,

@AArnott it crashed... have you download the project file and tried to load it into a VS 2015 RC build?  The zip file is there for anyone to take a look and use it.   

@madskristensen @sayedihashimi I am requesting this be reopened until a proper solution is arrived at.  I can't push my generator update to npm with an error like this.

**Comment by xtianus79** [comment]
@abpiskunov let me get this information for you today. 

> @xtianus79 I tried to open project attached in the zip in both RC and our latest current version and it loads fine and installs all bower and npm packages. After it is loaded it builds fine.

What exactly did you mean by " it seems to try to build it upon loading in the project.json"?

I need detailed info or repro steps:

what is the folder structure where your project lives on your machine (exception says path is too long, I tried to put it to very deep folder and it still worked)?
what dnx versions you have installed? What is your default dnx alias?
What settings do you have under Tools\Options\Projects and Solutions\External Web Tools?

**Comment by abpiskunov** [comment]
This issue is closed as by design. Those errors complaining for too long path are expected , please put your project to some shorter path.

**Comment by xtianus79** [comment]
@abpiskunov do you know what a node package is?

**Comment by abpiskunov** [comment]
@xtianus79 when I put your unzipped project in c:\temp and open it, it  loads fine and all packages are installed -  in all versions of VS: RC and current.
![npm](https://cloud.githubusercontent.com/assets/1592091/8058440/6ba6a3dc-0e87-11e5-8fe9-0bb69c12b045.png)

**Comment by xtianus79** [comment]
@abpiskunov I will try it again after an upgrade and report back to you exactly what versions of dnx and vs2015 i have installed.  Again, I have no control over how large of paths are created for npm and bower packages...

**Comment by xtianus79** [comment]
ok my VS is still not accepting the project.json. Doesn't crash but times out and offers an error message which is what is above.  The project folder is on the root in a test folder.  

 I am on Version 14.0228231.1 D14REL ... .net 4.6.00057

I am on a surface pro 3.  

dnvm is: 

 *    1.0.0-beta4 clr     x86          C:\Users\Christian\.dnx\runtimes default

**Comment by xtianus79** [comment]
@abpiskunov any update to this?  Is this perhaps a surface pro 3 thing?  because for me it won't work

**Comment by abpiskunov** [comment]
I still could not repro your problem, does it work if you try not a surface but some other machine?

**Comment by xtianus79** [comment]
@abpiskunov @madskristensen @sayedihashimi Here is an update as I have gotten around to installing this on my main gaming pc rig.  It is more than equipped to handle the most rigorous processes.  With that said, this is what I have found.  Visual studio will not crash if I have not preloaded the bower and npm modules.  Visual Studio will crash if those modules are preloaded or loaded thereafter... Meaning, if I wait to load bower/npm in VS 2015 then I won't be able to re-open VS any other time regarding that project.  Doesn't matter if I am using a project.json or sln... 

This has to be a major issues prior to deploying this in live.  Again, this was not an issue prior to RC.  On a positive note I did notice that when I have nothing proloaded and then load the bower/npm packages in I can run my gruntfile as intended.  There was a previous post I spoke about VS crashing when I had a lot of concurrent Grunt tasks loaded into my gruntfile.js.  

Finally, this seems to be purely an issue of VS trying to take on the bower_packages and node_modules folder into it's tree structure.  This should be prevented especially the node_modules... They should be hidden or automatically excluded from the project tree especially upon startup.  

Again, I am pretty certain what I am saying can be replicated as I have done it now on two PC's. 

Finally, I hope that VS can run on an I5 surface pro 3.  I mean that should be expected no?

**Comment by jodavis** [comment]
I was also unable to reproduce this crash on several recent builds, including the latest D14Rel, as well as VS 2015 RC. There must be some important factor missing, since it did reproduce on two different machines.

@xtianus79, are there any customizations common to your two PCs? For example, do you install any other VS extensions? Do you install Node.js or Git, and if so, what versions? Are there any other 3rd-party tools you use with this project?

**Comment by xtianus79** [comment]
@jodavis let me tell you what I do have installed... and how my configuration works.  

First I have on VS installed these extra's but all just VS options for RC:
Xamarin, android, git and perhaps a few other options... not silverlight.  
*** I have for the options of the path for VS I use my version of node.js as the path instead of using the VS version -- which is still at .10.  I did this by placing path ahead of the internal installation. 

Second, my versions of node are as such: 
node -v == 0.12.2
npm -v == 2.7.4
bower -v == 1.4.1
grunt-cli == 0.1.13

If there is a problem perhaps it is in the way VS uses the path of nodejs or otherwise.  

if there is any other information you need I would be glad to produce it.

**Comment by xtianus79** [comment]
@jodavis any update on this at all?

**Comment by xtianus79** [comment]
@abpiskunov any information on this?  I don't/can't update the npm package knowing that this build would break upon people using it via installing the npm package on the VS 2015 RC.  The npm build is far behind the git build.  Without any acknowledgement of this being an issue/bug of VS potentially 10's or 100's of people could download a failed build of my generator package. I wish for that not to occur.

**Comment by xtianus79** [comment]
How does this look on the released version? any updates?
