### ISSUE TITLE
An unhandled exception has occurred: Can not find compilation library location for package 'microsoft.csharp'

### ISSUE THREAD

**Issue by piotrpMSFT** [aspnet/Tooling#852]
Moved from https://github.com/dotnet/cli/issues/4343 on behalf of @xatabhk

----

## Steps to reproduce

Build and run  MusicStore sample
## Expected  behavior

No error.
## Actual behavior

An unhandled exception has occurred: Can not find compilation library location for package 'microsoft.csharp'

Full error message:
[error.txt](https://github.com/dotnet/cli/files/515774/error.txt)

![reference_not_found](https://cloud.githubusercontent.com/assets/6814395/19186032/d9ece62c-8cb6-11e6-9743-abb8753e7b8d.png)
## Environment data

`dotnet --info` output:
C:\temp\MusicStore-dev\samples\MusicStore>dotnet --info
.NET Command Line Tools (1.0.0-preview3-003716)

Product Information:
 Version:            1.0.0-preview3-003716
 Commit SHA-1 hash:  bbf9fe92cf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

**Comment by mlorbetske** [comment]
@xatabhk Would it be possible to the the full project.json added to the issue please?

@NTaylorMullen it looks like this is coming from Razor, while targeting 1.1 with project.json, any ideas?

```
at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
```

**Comment by xatabhk** [comment]
@mlorbetske It seems fixed in later versions.

**Comment by NTaylorMullen** [comment]
Good to know. @xatabhk it alright if I close this?

**Comment by xatabhk** [comment]
@NTaylorMullen I don't know. The packages download from here just didn't work on my PC. Only dotnet-dev-win-x86.1.0.0-preview2-1-003177.exe works.

**Comment by NTaylorMullen** [comment]
Ah, I see. You were using preview3 before (only understands csproj based projects) and when you downgraded to prewview2-1 (project.json understanding CLI) everything lit back up.

I can see why you were having errors before 👍
