### ISSUE TITLE
Error updating project tree after run gulp outside VS

### ISSUE THREAD

**Issue by cuiliang** [aspnet/Tooling#89]
![image](https://cloud.githubusercontent.com/assets/1972649/7905148/a74acb2c-0845-11e5-87e8-294266514588.png)

```
2015/6/1 10:01:42
Recoverable
System.AggregateException: One or more errors occurred. ---> Microsoft.Assumes+InternalErrorException: Error while updating project tree. ---> System.ArgumentException: An item with the caption "toaster.min.js" already exists in the tree with the same sort order as the item being added.
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(UnattachedProjectTreeNode node)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(IProjectTree subtree)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleAddedItem(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, String addedItem, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTreeSnapshot treeSnapshot, ConfiguredProjectExports configuredProjectExports, IProjectVersionedValue`1 update, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Assumes.Fail(String message, Exception innerException, Boolean showAssert)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTreeSnapshot treeSnapshot, ConfiguredProjectExports configuredProjectExports, IProjectVersionedValue`1 update, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<>c__DisplayClass167_0.<ProjectSubscriptionService_ChangedAsync>b__0(IProjectVersionedValue`1 treeSnapshot, ConfiguredProjectExports configuredProjectExports, CancellationToken ct)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass94_0.<<Initialize>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.Utilities.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.Assumes+InternalErrorException: Error while updating project tree. ---> System.ArgumentException: An item with the caption "toaster.min.js" already exists in the tree with the same sort order as the item being added.
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(UnattachedProjectTreeNode node)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectTree.Add(IProjectTree subtree)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleAddedItem(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, String addedItem, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTreeSnapshot treeSnapshot, ConfiguredProjectExports configuredProjectExports, IProjectVersionedValue`1 update, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Assumes.Fail(String message, Exception innerException, Boolean showAssert)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTreeSnapshot treeSnapshot, ConfiguredProjectExports configuredProjectExports, IProjectVersionedValue`1 update, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<>c__DisplayClass167_0.<ProjectSubscriptionService_ChangedAsync>b__0(IProjectVersionedValue`1 treeSnapshot, ConfiguredProjectExports configuredProjectExports, CancellationToken ct)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectTreeProviderBase.<>c__DisplayClass94_0.<<Initialize>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.Utilities.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

**Comment by taylorc** [comment]
I have exactly the same error when trying to update bower components from with visual studio 2015 professional

**Comment by sayedihashimi** [comment]
TFS:149647
I've added this to our internal TFS, we will reply back here soon.

**Comment by GearedToWar** [comment]
I am working on resolving this issue in the project system. I don't have permissions to assign in this repo to myself.

**Comment by sayedihashimi** [comment]
Sorry for the delay here. This issue is related to long paths. I heard back from the team that owns this component and they do not have plans to support long paths. If you run into this I think the best thing to do is to add your vote to http://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/4954037-fix-260-character-file-name-length-limitation.

There is nothing that my team can do about this issue, so I am closing this now.
