### ISSUE TITLE
VS2017 RC error MSB4166: Child node "2" exited prematurely.

### ISSUE THREAD

**Issue by SamirHafez** [aspnet/Tooling#939]
- Simple template console application (C# .NET Framework 4.6)
- Windows 10 15002
- Command line builds the project fine

Error:
`1>MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.`

opening the failure file:

```
UNHANDLED EXCEPTIONS FROM PROCESS 7540:
=====================
09/01/2017 19:29:07
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.ReadApplicationConfiguration()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.get_ConfigurationSection()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.<get_ToolsVersions>d__8.MoveNext()
   at Microsoft.Build.Evaluation.ToolsetReader.ReadEachToolset(Dictionary`2 toolsets, PropertyDictionary`1 globalProperties, PropertyDictionary`1 initialProperties, Boolean accumulateProperties)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadToolsets(Dictionary`2 toolsets, PropertyDictionary`1 globalProperties, PropertyDictionary`1 initialProperties, Boolean accumulateProperties, String& msBuildOverrideTasksPath, String& defaultOverrideToolsVersion)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader configurationReader, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetRegistryReader registryReader, ToolsetConfigurationReader configReader)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection.get_GlobalProjectCollection()
   at Microsoft.Build.Execution.OutOfProcNode.HandleNodeConfiguration(NodeConfiguration configuration)
   at Microsoft.Build.Execution.OutOfProcNode.HandlePacket(INodePacket packet)
   at Microsoft.Build.Execution.OutOfProcNode.Run(Boolean enableReuse, Exception& shutdownException)
   at Microsoft.Build.CommandLine.MSBuildApp.StartLocalNode(CommandLineSwitches commandLineSwitches)
   at Microsoft.Build.CommandLine.MSBuildApp.ProcessCommandLineSwitches(CommandLineSwitches switchesFromAutoResponseFile, CommandLineSwitches switchesNotFromAutoResponseFile, String& projectFile, String[]& targets, String& toolsVersion, Dictionary`2& globalProperties, ILogger[]& loggers, LoggerVerbosity& verbosity, List`1& distributedLoggerRecords, Boolean& needToValidateProject, String& schemaFile, Int32& cpuCount, Boolean& enableNodeReuse, TextWriter& preprocessWriter, Boolean& debugger, Boolean& detailedSummary, Boolean recursing)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
===================
09/01/2017 19:29:07
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.ReadApplicationConfiguration()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.get_ConfigurationSection()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.<get_ToolsVersions>d__8.MoveNext()
   at Microsoft.Build.Evaluation.ToolsetReader.ReadEachToolset(Dictionary`2 toolsets, PropertyDictionary`1 globalProperties, PropertyDictionary`1 initialProperties, Boolean accumulateProperties)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadToolsets(Dictionary`2 toolsets, PropertyDictionary`1 globalProperties, PropertyDictionary`1 initialProperties, Boolean accumulateProperties, String& msBuildOverrideTasksPath, String& defaultOverrideToolsVersion)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader configurationReader, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetRegistryReader registryReader, ToolsetConfigurationReader configReader)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection.get_GlobalProjectCollection()
   at Microsoft.Build.Execution.OutOfProcNode.HandleNodeConfiguration(NodeConfiguration configuration)
   at Microsoft.Build.Execution.OutOfProcNode.HandlePacket(INodePacket packet)
   at Microsoft.Build.Execution.OutOfProcNode.Run(Boolean enableReuse, Exception& shutdownException)
   at Microsoft.Build.CommandLine.MSBuildApp.StartLocalNode(CommandLineSwitches commandLineSwitches)
   at Microsoft.Build.CommandLine.MSBuildApp.ProcessCommandLineSwitches(CommandLineSwitches switchesFromAutoResponseFile, CommandLineSwitches switchesNotFromAutoResponseFile, String& projectFile, String[]& targets, String& toolsVersion, Dictionary`2& globalProperties, ILogger[]& loggers, LoggerVerbosity& verbosity, List`1& distributedLoggerRecords, Boolean& needToValidateProject, String& schemaFile, Int32& cpuCount, Boolean& enableNodeReuse, TextWriter& preprocessWriter, Boolean& debugger, Boolean& detailedSummary, Boolean recursing)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
===================
```

**Comment by olivier-spinelli** [comment]
Exact same behavior here. Any news?

**Comment by SamirHafez** [comment]
Retried it with the newest Windows 10 build (15014) with the same results...

...so no 😢

**Comment by olivier-spinelli** [comment]
Apparently, a VS2017 RC Repair should do the job. BUT, it fails. However, my failure was exactly the one described here: https://developercommunity.visualstudio.com/content/problem/4823/failure-during-repair-the-specified-account-alread.html

I'm currently reinstalling VS2017 RC... I'll tell you.

**Comment by olivier-spinelli** [comment]
Not better :(

**Comment by SamirHafez** [comment]
New update solved this
